kind: pipeline
name: package

clone:
  skip_verify: true
steps:
- name: build
  image: mono
  commands:
  - nuget restore
  - msbuild

- name: nuget
  image: mono
  commands:
  - nuget restore
  - msbuild
  - cd Dragon6-API
  - nuget setApiKey ${printenv $Key}
  environment:
    Key:
      from_secret: apiKey