kind: pipeline
name: package

clone:
  skip_verify: true
steps:
- name: build
  image: mono
  commands:
  - nuget restore
  - msbuild
  - nuget push Nuget/*.nupkg -k $$APIKEY
  environment:
    APIKEY:
      from_secret: Nuget
  when:
    branch:
    - master