kind: pipeline
name: package

clone:
  skip_verify: true
steps:
- name: build
  image: mono
  commands:
  - nuget restore
  - msbuild
- name: mirror
  image: alpine/git
  commands:
  - git push --mirror "https://$$LOGIN@github.com/dragonfruitnetwork/Dragon6-API.git"
  environment:
    LOGIN:
      from_secret: gitlogin