kind: pipeline
name: package

clone:
  skip_verify: true
steps:
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk
  commands:
  - dotnet restore
  - dotnet msbuild
  - cd Nuget
  - dotnet nuget push *.nupkg -k $$APIKEY -s https://api.nuget.org/v3/index.json
  environment:
    APIKEY:
      from_secret: Nuget
  when:
    branch:
    - master
- name: mirror
  image: alpine/git
  commands:
  - git push --mirror "https://$$LOGIN@github.com/dragonfruitnetwork/Dragon6-API.git"
  environment:
    LOGIN:
      from_secret: gitlogin