language: csharp
mono: none
dotnet: 2.2.203
dist: xenial
jobs:
  include:
  - stage: test
    script:
     - dotnet restore
     - dotnet build
     - cd "Dragon6-Test"
     - dotnet run
  - stage: pack
    script:
     - dotnet build -c Release
     - year=`date +%Y`
     - mon=`date +%m`
     - day=`date +%d`
     - dotnet pack "Dragon6-API/Dragon6-API.csproj" /p:PackageVersion=$year.$mon.$day -o .. -c Release 
     - dotnet nuget push *.nupkg -k $nugetkey -s "https://api.nuget.org/v3/index.json"
