language: csharp
dist: xenial
jobs:
  include:
  - stage: test
    mono: none
    dotnet: 2.2.203
    script:
     - dotnet restore
     - dotnet build
     - cd "Dragon6-Test"
     - dotnet run
  - stage: pack
    mono: latest
    script:
     - nuget restore Dragon6-API.sln
     - msbuild "Dragon6-API/Dragon6-API.csproj" /p:Configuration=Release
     - year=`date +%Y`
     - mon=`date +%m`
     - day=`date +%d`
     - nuget pack "Dragon6-API/Dragon6-API.csproj" -OutputDirectory "../" -Properties Configuration=Release PackageVersion=$year.$mon.$day
     - nuget push "./Dragon6.API.$year.$mon.$day.nupkg" -ApiKey $nugetkey -Source "https://api.nuget.org/v3/index.json"
