name: Test
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Test
      run: |
        dotnet restore
        dotnet build
        dotnet run --project Dragon6-Test
